# 训练配置
batch_size: 128
learning_rate: 0.001
epochs: 100
weight_decay: 0.0001
print_freq: 50  # 每多少个batch打印一次信息

# 分布式训练模式: single_gpu, multi_gpu, multi_node
distributed_mode: "single_gpu"

# 分布式训练配置
master_addr: "localhost"
master_port: "12355"

# 数据和模型保存配置
data_dir: "/mnt/data10/datasets"
save_dir: "/mnt/data10/model_checkpoints" 